---
# tasks file for sosreport

- name: Ensure sosreport is installed
  yum:
    name: sos
    state: present

- name: Create {{ sosreport_remote_dir }} directory
  file:
    path: "{{ sosreport_remote_dir }}"
    state: directory

- name: Create sosreport
  command: >
    /sbin/sosreport
      {% for arg in sosreport_args %}
        {{ arg }}
      {% endfor %}
      --tmp-dir="{{ sosreport_remote_dir }}"
      {% if sosreport_case is defined %}
        --case-id={{ sosreport_case }}
      {% endif %}
  environment: "{{ sosreport_env|default(omit) }}"

- name: Find files to fetch
  command: ls -1 {{ sosreport_remote_dir }}
  register: sosreport_files

- name: Fetch files to {{ sosreport_local_dir }} on the controller
  fetch:
    src: "{{ sosreport_remote_dir }}/{{ item }}"
    dest: "{{ sosreport_local_dir }}/"
    flat: yes
  with_items: "{{ sosreport_files.stdout_lines }}"

- name: Remove {{ sosreport_remote_dir }} directory
  file:
    path: "{{ sosreport_remote_dir }}"
    state: absent
